language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer install --prefer-dist --optimize-autoloader
    - vendor/bin/install-moco.sh

script:
    - vendor/bin/atoum -ulr
    - vendor/bin/behat -f progress
